version: "3"
services:
  backend:
    build: .
    tty: true
    ports:
      - 8080:8080
  frontend: # blockmine と blockmine-frontend を同じ階層におくこと
    build: ../blockmine-front/
    tty: true
    ports:
      - 3000:3000
